openapi: 3.0.1
info:
  title: Poke Backend
  version: 1.0.0
paths:
  '/test':
    get:
      operationId: test
      x-exegesis-controller: controller
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  '/getNodes':
    get:
      operationId: getNodes
      x-exegesis-controller: controller
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  '/getEdges':
    get:
      operationId: getEdges
      x-exegesis-controller: controller
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  '/getNodebyId':
    get:
      operationId: getNodebyId
      x-exegesis-controller: controller
      parameters:
      - description: node's id
        name: id
        in: query
        schema:
          type: string
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  '/updateNode':
    post:
      operationId: updateNode
      x-exegesis-controller: controller
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object
  '/changePlace':
    post:
      operationId: changePlace
      x-exegesis-controller: controller
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: idk
          content:
            application/json:
              schema:
                type: object